Repository kcl-lang/kpm, pull requests merged in 2023-10, with the labels that each got.

#196 fix: bump the latest version of k8s in test case
  pkg/client/client_test.go
Labels: bug

#194 feat: add 'kpm import' to converts other formats to KCL file
  docs/command-reference-zh/11.import.md
  docs/command-reference/11.import.md
  go.mod
  go.sum
  kpm.go
  pkg/cmd/cmd_import.go
  test/e2e/test_suites/kpm/exec_outside_pkg/help_msg/test_suite.stdout
Labels: tool

#198 fix: 'kpm run' will trigger the automatic download of the dependencies
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/client/test_data/resolve_dep_with_kclmod/kcl.mod
  pkg/client/test_data/resolve_dep_with_kclmod/main.k
  test/e2e/test_suites/kpm/kpm_run/test_kpm_run_with_only_kcl_mod/test_suite.env
  test/e2e/test_suites/kpm/kpm_run/test_kpm_run_with_only_kcl_mod/test_suite.input
  test/e2e/test_suites/kpm/kpm_run/test_kpm_run_with_only_kcl_mod/test_suite.stderr
  test/e2e/test_suites/kpm/kpm_run/test_kpm_run_with_only_kcl_mod/test_suite.stdout
  test/e2e/test_suites/test_data/test_kpm_run_with_only_kcl_mod/kcl.mod
  test/e2e/test_suites/test_data/test_kpm_run_with_only_kcl_mod/main.k
Labels: bug

#205 feat: add metadata into oci manifest when 'kpm push'
  go.mod
  go.sum
  pkg/client/client.go
  pkg/cmd/cmd_push.go
  pkg/constants/constants.go
  pkg/oci/oci.go
  pkg/opt/opt.go
  pkg/package/modfile.go
  pkg/package/modfile_test.go
  pkg/package/package.go
  pkg/package/test_data/test_mod_with_desc/kcl.mod
  pkg/package/test_data/test_mod_with_desc/kcl.mod.lock
  pkg/package/test_data/test_mod_with_desc/main.k
  pkg/package/toml.go
  test/e2e/kpm_test.go
  test/e2e/test_suites/kpm/test_oci/test_push_with_oci_manifest/test_suite.env
  test/e2e/test_suites/kpm/test_oci/test_push_with_oci_manifest/test_suite.input
  test/e2e/test_suites/kpm/test_oci/test_push_with_oci_manifest/test_suite.stderr
  test/e2e/test_suites/kpm/test_oci/test_push_with_oci_manifest/test_suite.stdout
  test/e2e/test_suites/test_data/test_push_with_oci_manifest/expected_oci_manifest.json
  test/e2e/test_suites/test_data/test_push_with_oci_manifest/kcl.mod
  test/e2e/test_suites/test_data/test_push_with_oci_manifest/kcl.mod.lock
  test/e2e/test_suites/test_data/test_push_with_oci_manifest/main.k
Labels: enhancement

#206 feat: Add a method to KpmClient to fetch the oci manifest
  pkg/client/client.go
  pkg/oci/oci.go
  pkg/opt/opt.go
  scripts/pkg_in_reg/kcl1/kcl.mod
  scripts/pkg_in_reg/kcl2/kcl.mod
  test/e2e/kpm_test.go
Labels: enhancement

#207 chore: bump kpm version from 0.3.6 to 0.3.7
  go.mod
  go.sum
  pkg/version/version.go
  pkg/version/version_test.go
Labels: enhancement

#208 doc: add docs for 'publish kcl package'
  README-zh.md
  README.md
  docs/publish_pkg_to_ah-zh.md
  docs/publish_pkg_to_ah.md
Labels: documentation

#210 fix: fix panic error when 'kpm run <oci_url>'
  go.mod
  go.sum
  pkg/client/client.go
  test/e2e/test_suites/kpm/exec_outside_pkg/kpm_pull_with_oci_url/test_suite.stdout
  test/e2e/test_suites/kpm/exec_outside_pkg/kpm_pull_with_oci_url_tag/test_suite.stdout
  test/e2e/test_suites/kpm/exec_outside_pkg/kpm_pull_with_pkg_name/test_suite.stdout
  test/e2e/test_suites/kpm/exec_outside_pkg/kpm_pull_with_pkg_name_tag/test_suite.stdout
  test/e2e/test_suites/kpm/exec_outside_pkg/kpm_run_oci_url/test_suite.env
  test/e2e/test_suites/kpm/exec_outside_pkg/kpm_run_oci_url/test_suite.input
  test/e2e/test_suites/kpm/exec_outside_pkg/kpm_run_oci_url/test_suite.stderr
  test/e2e/test_suites/kpm/exec_outside_pkg/kpm_run_oci_url/test_suite.stdout
  test/e2e/test_suites/kpm/exec_outside_pkg/kpm_run_oci_url_quiet/test_suite.env
  test/e2e/test_suites/kpm/exec_outside_pkg/kpm_run_oci_url_quiet/test_suite.input
  test/e2e/test_suites/kpm/exec_outside_pkg/kpm_run_oci_url_quiet/test_suite.stderr
  test/e2e/test_suites/kpm/exec_outside_pkg/kpm_run_oci_url_quiet/test_suite.stdout
Labels: bug
